#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'rvm',
  :git => "https://github.com/get-vitamin-c/chef-rvm"
cookbook 'git'
cookbook 'postgresql'
cookbook 'mongodb'
cookbook 'nodejs'
cookbook 'redisio'
cookbook 'sidekiq'
